import { StyleSheet, Platform } from 'react-native';
import { theme } from '../styles/theme';

export const styles = StyleSheet.create({
  safeArea: { 
    flex: 1, 
    backgroundColor: '#f8fafc',
  },
  scrollContent: { 
    paddingBottom: 100,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 16,
    backgroundColor: '#f8fafc',
  },
  welcomeSection: { 
    flex: 1,
  },
  welcomeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  title: { 
    fontSize: 22, 
    fontWeight: '800', 
    color: '#0f172a', 
  },
  waveBadge: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#eff6ff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  waveText: {
    fontSize: 16,
  },
  subtitle: { 
    fontSize: 12, 
    color: '#64748b',
    fontWeight: '500',
    marginTop: 2,
  },
  addEventBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2563eb',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 24,
    shadowColor: '#2563eb',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.28,
    shadowRadius: 8,
    elevation: 4,
    gap: 8,
  },
  addEventIconCircle: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#ffffff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  addEventPlusText: {
    color: '#2563eb',
    fontSize: 12,
    fontWeight: '900',
    marginTop: -1,
  },
  addEventBtnText: { 
    color: '#ffffff', 
    fontSize: 12, 
    fontWeight: '700',
  },
  container: { 
    paddingHorizontal: 20,
  },
  sectionHeader: {
    fontSize: 11,
    fontWeight: '700',
    color: '#64748b',
    letterSpacing: 0.8,
    marginTop: 18,
    marginBottom: 12,
  },
  statsRow: { 
    flexDirection: 'row', 
    gap: 12, 
    width: '100%', 
    marginBottom: 16,
  },
  statCard: {
    flex: 1, 
    backgroundColor: '#ffffff', 
    borderRadius: 20, 
    padding: 16,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 4 }, 
    shadowOpacity: 0.04,
    shadowRadius: 10, 
    elevation: 2,
    borderWidth: 1, 
    borderColor: '#f1f5f9',
  },
  statIconBadge: {
    width: 38,
    height: 38,
    borderRadius: 19,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  statIcon: {
    width: 18,
    height: 18,
  },
  statValue: { 
    fontSize: 22, 
    fontWeight: '800', 
    marginBottom: 2,
  },
  statLabel: { 
    fontSize: 11, 
    fontWeight: '600', 
    color: '#64748b',
  },
  infoBar: {
    width: '100%', 
    flexDirection: 'row', 
    justifyContent: 'space-between',
    alignItems: 'center', 
    backgroundColor: '#ffffff', 
    borderRadius: 16,
    paddingHorizontal: 16, 
    paddingVertical: 12, 
    marginBottom: 16,
    borderWidth: 1, 
    borderColor: '#f1f5f9',
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 6,
    elevation: 1.5,
  },
  infoBarText: { 
    fontSize: 12, 
    fontWeight: '600',
    color: '#334155',
  },
  refreshBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#eff6ff',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    gap: 4,
  },
  refreshText: { 
    fontSize: 11, 
    fontWeight: '700', 
    color: '#2563eb',
  },
  
  // Event Cards
  eventCard: {
    backgroundColor: '#ffffff',
    borderRadius: 22,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#f1f5f9',
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 10,
    elevation: 2,
  },
  eventCardTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    marginBottom: 12,
  },
  eventThumbnail: {
    width: 60,
    height: 60,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
  },
  eventThumbnailIcon: {
    width: 28,
    height: 28,
    tintColor: '#ffffff',
  },
  eventMetaContainer: {
    flex: 1,
  },
  eventName: { 
    fontSize: 15, 
    fontWeight: '700', 
    color: '#0f172a', 
    marginBottom: 5,
  },
  eventMetaRow: { 
    flexDirection: 'row', 
    alignItems: 'center', 
    marginBottom: 3,
  },
  eventMetaIcon: { 
    width: 12, 
    height: 12, 
    tintColor: '#94a3b8',
    marginRight: 6,
  },
  eventMetaText: { 
    fontSize: 11, 
    color: '#64748b',
    fontWeight: '500',
  },
  eventArrow: {
    fontSize: 20,
    color: '#3b82f6',
    fontWeight: '600',
    paddingHorizontal: 4,
  },
  eventDivider: { 
    height: 1, 
    backgroundColor: '#f1f5f9', 
    marginVertical: 10,
  },
  eventStatsGrid: { 
    flexDirection: 'row', 
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  eventStatCol: {
    flex: 1,
    alignItems: 'center',
  },
  eventStatColLabel: {
    fontSize: 10,
    color: '#94a3b8',
    fontWeight: '600',
    marginBottom: 3,
  },
  eventStatColVal: {
    fontSize: 14,
    fontWeight: '800',
  },
  eventStatColDivider: {
    width: 1,
    height: 22,
    backgroundColor: '#f1f5f9',
  },
  emptyCard: { 
    backgroundColor: '#ffffff', 
    borderRadius: 20, 
    padding: 24, 
    borderWidth: 1, 
    borderStyle: 'dashed', 
    borderColor: '#cbd5e1', 
    alignItems: 'center',
    marginTop: 8,
  },
  emptyText: { 
    color: '#64748b', 
    fontSize: 12, 
    textAlign: 'center', 
    lineHeight: 18,
  },

  // Modal Styles
  modalOverlay: { 
    flex: 1, 
    backgroundColor: 'rgba(0, 0, 0, 0.5)', 
    justifyContent: 'center', 
    alignItems: 'center', 
    padding: 24 
  },
  modalContent: { 
    backgroundColor: '#ffffff', 
    borderRadius: 28, 
    width: '100%', 
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 20,
    shadowColor: '#0f172a', 
    shadowOffset: { width: 0, height: 10 }, 
    shadowOpacity: 0.15, 
    shadowRadius: 24, 
    elevation: 12, 
  },
  dragHandleBar: {
    width: 38,
    height: 4.5,
    borderRadius: 2.5,
    backgroundColor: '#cbd5e1',
    alignSelf: 'center',
    marginBottom: 12,
  },
  modalHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  modalHeaderLeft: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 10,
  },
  modalThumbnail: {
    width: 44,
    height: 44,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  modalThumbnailIcon: {
    width: 22,
    height: 22,
    tintColor: '#ffffff',
  },
  modalTitleCol: {
    flex: 1,
  },
  modalSheetTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#0f172a',
    marginBottom: 2,
  },
  modalSheetSub: {
    fontSize: 11,
    color: '#64748b',
    fontWeight: '500',
  },
  modalCloseBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#f1f5f9',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  modalCloseIcon: {
    width: 11,
    height: 11,
    tintColor: '#64748b',
  },

  // Tier breakdown di modal detail
  detailTierContainer: {
    marginBottom: 14,
  },
  detailTierHeader: {
    fontSize: 10.5,
    fontWeight: '800',
    color: '#64748b',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  detailTierGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  detailTierCard: {
    width: '48.5%',
    flexDirection: 'row',
    alignItems: 'center',
    padding: 9,
    borderRadius: 14,
    borderWidth: 1.2,
  },
  detailTierIconBadge: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: '#ffffff',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
    borderWidth: 1,
  },
  detailTierIcon: {
    width: 16,
    height: 16,
  },
  detailTierInfo: {
    flex: 1,
  },
  detailTierLabel: {
    fontSize: 12,
    fontWeight: '800',
    marginBottom: 1,
  },
  detailTierCount: {
    fontSize: 10,
    fontWeight: '700',
    color: '#475569',
  },

  // Action Buttons
  modalActionBtn: { 
    flexDirection: 'row',
    backgroundColor: '#2563eb', 
    height: 44, 
    borderRadius: 14, 
    alignItems: 'center', 
    justifyContent: 'center',
    marginBottom: 8,
    shadowColor: '#2563eb',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 5,
    elevation: 3,
    gap: 6,
  },
  modalActionBtnIcon: {
    width: 16,
    height: 16,
    tintColor: '#ffffff',
  },
  modalActionBtnText: { 
    color: '#ffffff', 
    fontSize: 13, 
    fontWeight: '800',
  },
  modalHistoryBtn: { 
    flexDirection: 'row',
    backgroundColor: '#eff6ff', 
    borderWidth: 1, 
    borderColor: '#bfdbfe', 
    height: 44, 
    borderRadius: 14, 
    alignItems: 'center', 
    justifyContent: 'center',
    gap: 6,
  },
  modalHistoryBtnIcon: {
    width: 15,
    height: 15,
    tintColor: '#2563eb',
  },
  modalHistoryBtnText: { 
    color: '#2563eb', 
    fontSize: 13, 
    fontWeight: '700',
  },

  // Form Styles (Buat Event Baru)
  formGroup: { 
    marginBottom: 12,
  },
  formLabel: { 
    fontSize: 9.5, 
    fontWeight: '800', 
    color: '#64748b', 
    letterSpacing: 0.8, 
    marginBottom: 5,
    textTransform: 'uppercase',
  },
  formInputWithIcon: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 12,
    paddingHorizontal: 12,
    minHeight: 44,
  },
  formInputIcon: {
    width: 16,
    height: 16,
    tintColor: '#2563eb',
    marginRight: 10,
  },
  formInputText: {
    flex: 1,
    fontSize: 13,
    color: '#0f172a',
    paddingVertical: 8,
  },
  formHint: { 
    fontSize: 10, 
    color: '#94a3b8', 
    marginTop: 3,
    marginLeft: 2,
  },
  formErrorBox: {
    backgroundColor: '#fef2f2', 
    borderRadius: 12, 
    padding: 10,
    borderWidth: 1, 
    borderColor: '#fecaca', 
    marginBottom: 12,
  },
  formErrorText: { 
    fontSize: 12, 
    color: '#dc2626', 
    lineHeight: 17,
  },
});
