import { StyleSheet } from 'react-native';
import { theme } from '../styles/theme';

export const styles = StyleSheet.create({
  safeArea: { 
    flex: 1, 
    backgroundColor: '#f8fafc',
  },
  content: { 
    flex: 1, 
    paddingHorizontal: 20, 
    paddingTop: 12,
  },
  avatarCard: {
    backgroundColor: '#eff6ff', // Soft light blue tint hero card
    borderRadius: 24,
    padding: 24,
    alignItems: 'center',
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#dbeafe',
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 10,
    elevation: 2,
  },
  avatar: {
    width: 76,
    height: 76,
    borderRadius: 38,
    backgroundColor: '#2563eb', // Royal Blue circle
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
    borderWidth: 4,
    borderColor: '#ffffff',
    shadowColor: '#2563eb',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 4,
  },
  avatarLetter: { 
    fontSize: 32, 
    fontWeight: '800', 
    color: '#ffffff',
  },
  username: { 
    fontSize: 20, 
    fontWeight: '800', 
    color: '#0f172a', 
    marginBottom: 8,
  },
  roleBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#bfdbfe',
    gap: 6,
    shadowColor: '#2563eb',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 1,
  },
  roleIcon: {
    width: 14,
    height: 14,
    tintColor: '#2563eb',
  },
  roleText: { 
    fontSize: 10.5, 
    fontWeight: '800', 
    color: '#2563eb', 
    letterSpacing: 0.5,
  },
  
  // Panduan Scanner Card
  infoCard: {
    backgroundColor: '#ffffff',
    borderRadius: 22,
    padding: 20,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#f1f5f9',
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 10,
    elevation: 2,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 16,
  },
  sectionIconBadge: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: '#eff6ff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  sectionIcon: {
    width: 16,
    height: 16,
    tintColor: '#2563eb',
  },
  infoTitle: {
    fontSize: 11.5,
    fontWeight: '700',
    color: '#64748b',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  layerRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  layerRowLast: { 
    borderBottomWidth: 0,
    paddingBottom: 2,
  },
  layerIcon: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#2563eb',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
    marginTop: 2,
    shadowColor: '#2563eb',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  layerIconText: { 
    fontSize: 13, 
    fontWeight: '800', 
    color: '#ffffff',
  },
  layerText: { 
    flex: 1,
  },
  layerTitle: { 
    fontSize: 13.5, 
    fontWeight: '700', 
    color: '#0f172a', 
    marginBottom: 2,
  },
  layerDesc: { 
    fontSize: 11.5, 
    color: '#64748b', 
    lineHeight: 16,
  },
  
  // App Info Card
  appInfoCard: {
    backgroundColor: '#ffffff',
    borderRadius: 22,
    padding: 20,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#f1f5f9',
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 10,
    elevation: 2,
  },
  appInfoRowContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 4,
  },
  appInfoLabel: { 
    width: 60,
    fontSize: 12,
    color: '#64748b', 
    fontWeight: '500',
  },
  appInfoColon: {
    width: 16,
    fontSize: 12,
    color: '#94a3b8',
    fontWeight: '600',
  },
  appInfoValue: { 
    fontSize: 12,
    color: '#0f172a', 
    fontWeight: '700',
  },
  
  // Action Buttons
  buttonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    marginTop: 4,
  },
  resetButton: {
    flex: 1,
    height: 48,
    backgroundColor: '#ef4444',
    borderRadius: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#ef4444',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 3,
    gap: 6,
  },
  resetButtonText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '700',
  },
  logoutButton: {
    flex: 1,
    height: 48,
    backgroundColor: '#dc2626',
    borderRadius: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#dc2626',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 3,
    gap: 6,
  },
  logoutText: { 
    color: '#ffffff', 
    fontWeight: '700', 
    fontSize: 13,
  },
});
