import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#f8f9fa' },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 16,
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
  },
  headerTitle: { fontSize: 20, fontWeight: 'bold', color: '#212529' },
  headerCount: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#007BFF', // Azure Blue
    backgroundColor: '#eff6ff',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
  },
  listContainer: { paddingHorizontal: 24, paddingVertical: 24 },
  listContainerEmpty: { flex: 1 },
  historyItem: {
    flexDirection: 'row',
    marginBottom: 0,
  },
  timelineCol: {
    width: 32,
    alignItems: 'center',
    paddingTop: 16,
  },
  timelineDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#007BFF', // Azure Blue
    borderWidth: 2,
    borderColor: '#ffffff',
    shadowColor: '#007BFF',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 4,
    elevation: 3,
  },
  timelineLine: {
    flex: 1,
    width: 2,
    backgroundColor: '#e2e8f0',
    marginTop: 4,
    marginBottom: -4,
  },
  historyCard: {
    flex: 1,
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 16,
    marginLeft: 12,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  historyCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 6,
  },
  historyEvent: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#212529',
    flex: 1,
    marginRight: 8,
  },
  statusBadge: {
    backgroundColor: '#f7fee7', // Lime Green bg
    borderRadius: 6,
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderWidth: 1,
    borderColor: '#d9f99d',
  },
  statusText: {
    fontSize: 9,
    fontWeight: 'bold',
    color: '#84cc16', // Lime Green text
    letterSpacing: 0.5,
  },
  typeBadge: {
    borderRadius: 6,
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderWidth: 1,
  },
  typeBadgeText: { fontSize: 9, fontWeight: 'bold', letterSpacing: 0.5 },
  historyEventDate: { fontSize: 12, color: '#6c757d', marginBottom: 10 },
  historyMeta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
    paddingTop: 8,
  },
  historyTicketId: {
    fontSize: 10,
    color: '#94a3b8',
    fontFamily: 'monospace',
  },
  historyTime: { fontSize: 10, color: '#94a3b8' },
  emptyContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 40,
  },
  emptyIcon: { fontSize: 64, marginBottom: 16 },
  emptyTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#212529',
    marginBottom: 8,
  },
  emptySubtitle: {
    fontSize: 13,
    color: '#6c757d',
    textAlign: 'center',
    lineHeight: 20,
  },
});
